### ISSUE TITLE
add HTTPC change retry

### ISSUE THREAD

**Issue by BernardNotarianni** [barrel-db/barrel-platform#103]
We want to add a mecanism of retry/connect in httpc_change enabling to continue the replication mecanism, even in case the HTTP server timeout.

We might use an exponential backoff such as https://github.com/ferd/backoff

**Comment by BernardNotarianni** [comment]
TODO: add edoc for new options

**Comment by benoitc** [comment]
closing, issue has been moved to Gitlab. Please track the changes on this issue there:
https://gitlab.com/barrel-db/barrel-platform/issues/103
