### ISSUE TITLE
Docs_count misbehavior 

### ISSUE THREAD

**Issue by deadtrickster** [barrel-db/barrel-platform#106]
#### Description :octocat:

When my app starts it upserts **two** documents (exactly the same each time, same ids, same data? (not 100% sure here, it decodes certificates first, so maybe some timestamps involved)).
docs_count stat always increments :shrimp: 

#### Reproduction guide :beetle:

*at random point of time*:
`{"docs_count":10,"id":"message_gateway","last_index_seq":2,"last_update_seq":10,"name":"message_gateway","system_docs_count":0}`

after two debugging sessions:

`{"docs_count":14,"id":"message_gateway","last_index_seq":2,"last_update_seq":14,"name":"message_gateway","system_docs_count":0}`

after replacing `post` with `put`:

`{"docs_count":18,"id":"message_gateway","last_index_seq":18,"last_update_seq":18,"name":"message_gateway","system_docs_count":0}`

Exactly the same :-) except `last_index_seq` caught up. I suppose it's background indexer.

**Comment by benoitc** [comment]
Issue has been moved to Gitlab: https://gitlab.com/barrel-db/barrel-platform/issues/106 Please track update there.
