### ISSUE TITLE
add bulk docs upload

### ISSUE THREAD

**Issue by benoitc** [barrel-db/barrel-platform#57]
Right now we can only send one doc per request.We should also be able to push multiple docs at once over HTTP. 

API proposal:

a `POST` request is done on `/dbs/<dbname>/docs` with a JSON containing a list of documents passed with their revision (optionnaly) to the `docs` property : 

```
POST /dbs/<dbname>/docs HTTP 1/1 
x-barrel-isbulk: true
Content-Type: application/json

{ "docs" : [ 
  { "doc":  { "id": "doc1", ... }, "rev": "rev" }
 ...
]}
```

The response return the list of document updated with their revisions:

```
POST /dbs/<dbname>/docs HTTP 1/1 
x-barrel-isbulk: true
Content-Type: application/json

{ "docs" : [ 
   { "status": "ok", "id": "doc1", "rev": "" }
 ...
]}
```

If a conffict happened it is returned associated to the document id:  `{ "id": "doc", "status": "conflict", "conflict": "typeofconflict"}`

Optionally the header `x-barrel-replicated: true` will be given to tell we are sending new revisions.

Thoughts?

**Comment by BernardNotarianni** [comment]
The HTTP API seems all good to me.

For implementation, we would call `barrel_local:put` for each document to be created, correct?

**Comment by benoitc** [comment]
@BernardNotarianni nope you should rather use `barrel_db:update_docs`for it that already handle the multi doc updates. Just that it is not exposed now.

**Comment by BernardNotarianni** [comment]
Plan

- [ ] expose `barrel_db:updated_docs`

- [ ] implement HTTP API for buld update

- [ ] expose `barrel_httpc:updated_docs`

**Comment by benoitc** [comment]
I will need to make a change in the return of `barrel_db:update_docs` so please wait :)

**Comment by BernardNotarianni** [comment]
I guess we should have a bulk `HTTP POST` accepting only document creations and a bulk `HTTP PUT` to only update existing documents.

Exact?

**Comment by benoitc** [comment]
mm no just a post and doc will be created or a conflict returned

**Comment by benoitc** [comment]
@BernardNotarianni I to accept put, post and delete in one call, and consider it as a bulk:

on `POST /dbs/<db>/docs`:

```
[
     { "op": "put", "doc": {},  "rev": "" },
     {"op": "delete", "docid", "rev" },
     {"op": "post", "doc": {} 
]
```

rev is always optional. OPS are corresponding to what could be done on one doc. In `barrel_local` then a better naming to the function could be `update_docs` as you said it sooner ....
