### ISSUE TITLE
add multi docs download

### ISSUE THREAD

**Issue by benoitc** [barrel-db/barrel-platform#58]
Right now we can only get one doc at once based on its document id. The proposal is introducing a new API to get multi documents by their IDs at once.

This API will be useful to also speed the replication.

API change

A `POST` request is done on `/dbs/<dbname>/docs` with the header `x-barrel-mget: true` witht eh list of document ids and their revisions:

```
POST /dbs/<dbname>/dosc HTTP/1.1
x-barrel-mget: true
content-type: text/json

{
    "docs": [
       {"id": "docid", "revs": [ "revid1", ... ] },
       ...
    ]
}
```

The `revs` property is optional and if not given, the last will be returned. The response returned is the following:

```
{
    "docs": [
       {"id": "docid", "rev:" "revid", "doc": { ... } }
   ]
}
```

Optionally the parameter `history=true` can be be passed to return each revisions with its history. It will be useful for the replication.

**Comment by benoitc** [comment]
depends on #59 since it will make the API stable on the long term.

**Comment by BernardNotarianni** [comment]
I am not fully convinced by this `POST` request on `/dbs/<dbname>/docs`.
I would prefer this route to looks like a query more than like a document creation.

@benoitc what is the expected API for queries?

I would expect something like a `POST` on `/dbs/<dbname>/query`.
Then, this "multi docs download" request could be on same route, whit a header indicating that the syntax of the query is specific (like asking documents one by one, rather than by a document set functional filter)

Does it make sense?

**Comment by BernardNotarianni** [comment]
Headers could be:
- `x-barrel-query: mget` for multiple get
- `x-barrel-query: bql` for the upcoming Barrel Query Langage (this could be the default I guess)

**Comment by BernardNotarianni** [comment]
Moreover, maybe the route should be `/dbs/<dbname>/queries` to respect the current convention of plurial for collections.

**Comment by benoitc** [comment]
i don't see how posting docs are related to a query .... While I am ok to handle queries at a `query` point I feel more natural **to post docs** on `docs`.

**Comment by benoitc** [comment]
so `x-barrel-query: mget` to get multiple doc  and `x-barrel-query: bulk-upload` on POST on docs is what I would like to have imo.  I think that rather than `mget` we may want `bulk-get` though. Thoughts?

**Comment by BernardNotarianni** [comment]
> I don't see how posting docs are related to a query

Neither me. That is why I propose to **not** use the route `POST /dbs/<dbname>/doc` to get documents.

> I feel more natural to post docs on docs.

Fully agree on this one, which I guess is related to #57 

I am not sure you fully understand why i propose. I reformulate:

I propose to add those two new routes:

1) `POST /dbs/<dbname>/query` with body containing the list of of documents **we want to get**, as [you described it](https://github.com/barrel-db/barrel-platform/issues/58#issue-209480529) in this issue

2) `POST /dbs/<dbname>/docs` with body containing the list of of documents **to be added**, as [you descibed it](https://github.com/barrel-db/barrel-platform/issues/57#issue-209477699), for issue #57 . 

Thoughts?

**Comment by benoitc** [comment]
I edited #58 . I meant `docs` not doc.  So the clarify:

* Anything to *get/upload/delete* docs in bulk or not *must* be on `docs`(this is the resource where we manage docs.  
* Anything to query docs (like walk or coming query engine) should be done on another resource since it's not per see a view on docs but rather a dynamic collection.

**Comment by BernardNotarianni** [comment]
After dicussion with @benoitc we converged with the following API for the multi docs download:

`GET` on `/dbs/<dbname>/docs` with a specific HTTP header giving the list of docid to retrieve.

Example:
```
GET /dbs/<dbname>/docs
x-barrel-id-match: docid1, docid2, docid3
x-barrel-id-match: docid4, docid5, docid6
```
The docid are separed by a comma. We can repeat the header `x-barrel-id-match` several times in the same request.
