### ISSUE TITLE
move docker image in the repo?

### ISSUE THREAD

**Issue by benoitc** [barrel-db/barrel-platform#63]
should we move the docker image in the repo? cc @BernardNotarianni

**Comment by BernardNotarianni** [comment]
Not sure to understand what you mean here.

Are you asking if we should move the dockerfile to create the docker image into this repo?
I would say no.

However, we might want to move the repository of the dockerfiles from gitlab to github.

**Comment by benoitc** [comment]
I was thinking that since we are a mono repo it could be easier to move it there. But no strong opinion on it. At least we should move it yes :)

**Comment by BernardNotarianni** [comment]
The mono repo would contains everything needed to build a working barrel artifact (a set of erlang applications) This is a **converging** process of feature branches into one artifact.

Then I would put this artefact into different kind of containers such as snap, docker, vagrant, etc.. This is a **diverging** process which looks different to me.

Now, we could put all the configuration for images (docker, vagrant, etc..) in one repo, but I am not sure this is best practice. (I don't known actually)

**Comment by benoitc** [comment]
done. [barrel-docker](https://github.com/barrel-db/barrel-docker) repo created.
