### ISSUE TITLE
allow sending document metadata only in headers?

### ISSUE THREAD

**Issue by benoitc** [barrel-db/barrel-platform#75]
Maybe we could have an option to not send the doc with the `_meta` object in normal get. Like having an header `x-barrel-with-meta: false` . Not sure about the default. In such case only the revision would be sent as an `ETag` header. Possibly we could also send the resource id as `x-barrel-rid: Rid`. It would allows the client to not have to edit the doc and extract the `_meta`part from it.

Thoughts?

**Comment by benoitc** [comment]
another possibility is to not send the `_meta` object at all and only add an extra part like `_revisions` to the body when it's requested. In such case the metadata would only be available via headers. I think I like this more than the proposal above.

**Comment by benoitc** [comment]
cc @BernardNotarianni

**Comment by BernardNotarianni** [comment]
I have the feeling that the "purest" form of REST would be:
1. No meta at all in the document. The document is purely, and only, the data the user put in it. Nothing more, nothing less.
2. All the meta are in headers.

In such an approach, I would not event give the opportunity to have the optional `_revisions` prop in document.

**Comment by benoitc** [comment]
@BernardNotarianni I agree but I don't see any other possibilities to get the conflicting revisions for a document. Or how would you sent them?

**Comment by BernardNotarianni** [comment]
In a header, as you suggested? (or did I miss something?)

**Comment by benoitc** [comment]
@BernardNotarianni the idea is to send all the conflicting revisions in 1 call. So a conflicting revision with its body would like go in an header...

If we don't edit the doc maybe we should then add the following path:
- `/dbs/<dbname>/docs/docid/conflicts`: path to return all conflicts with their body

These two paths would replace the current additions to the metadata.

- `/dbs/<dbname>/docs/docid` could still accept the current parameters. But how would you send a long history? Currently we are sending

`  #{ <<"start">> := Start, <<"ids">> := Digests} ` in the `revision`metadata .

Also what would be the good way to retrieve the document *and* its conflicting revisions in 1 call? Just by using the `docs` API addition described in #76 ?

**Comment by benoitc** [comment]
Thinking about it we could send :

```http
x-revisions-start: Start
x-revisions-id: id1
x-revisions-id: id2
```

Thoughts?

**Comment by BernardNotarianni** [comment]
No sure the `x-revisions-start` is usefull. Why not just use several `x-revisions-id` containing lists of revisions?

**Comment by benoitc** [comment]
if we send the revisions as a list that will probably work too indeed :)

**Comment by BernardNotarianni** [comment]
## `GET /dbs/<db>/docid/<id>`
return
```text
HTTP/1.1 200
etag: 1-5c1f0a9d721f0731a46645d18b763047
{
  "id": "theid",
  "value": "value"
}
```

**Comment by BernardNotarianni** [comment]
@benoitc We need also a way to indicate the document has been deleted. What about a `x-barrel-deleted: true` header?
