### ISSUE TITLE
update barrel_httpc repo

### ISSUE THREAD

**Issue by BernardNotarianni** [barrel-db/barrel-platform#77]
We should update the [barrel_httpc standalone repo](https://github.com/barrel-db/barrel_httpc) with the very last version of the library.

@benoitc could you please do it and/or describe the procedure?

**Comment by benoitc** [comment]
done in https://github.com/barrel-db/barrel_httpc/commit/370391d91675a9e1cf4bc5ac15746d57ba73f34d

**Comment by benoitc** [comment]
we need to find a better way to do it though. Right now I'm using the subtree command of git but we may want to use [splitsh](https://github.com/splitsh/lite) or equivalent tool (so we also keep the history)
