### ISSUE TITLE
list of barrel metrics to support

### ISSUE THREAD

**Issue by benoitc** [barrel-db/barrel-platform#81]
Following a conversation with @BernardNotarianni  I will list there the metrics that could be useful to give a good image of the activity of barrel in production but also during the benchmarks.

## DB business metrics:

- [ ] number of  docs (gauge)  
- [ ] number of docs created (counter)
- [ ] number of docs deleted (counter)
- [ ] number of docs updated (counter)
- [ ] number of revisions replicated (counter)
- [ ] number of docs indexing (counter)
- [ ] numbers of docs indexed (counter)
- [ ] doc size (gauge) 
- [ ] size of the db storage (gauge) 
- [ ] size of the index storage (gauge)
- [ ] number of keys indexed (gauge)
- [ ] number of unmerged keys (gauge)
- [ ] memory usage for the index (gauge)
- [ ] object cache usage (gauge) 
- [ ] number of changes feeds running (counter)

## Global business metrics

- [ ] number of replication tasks (gauge)
- [ ] number of replication tasks running (counter)
- [ ] number of databases (gauge)

## replication metrics

- [ ] number of  docs reads (counter)
- [ ] number of  docs reads failures  (counter)
- [ ] doc read time (?)
- [ ] number of doc writes (counter)
- [ ] number of doc writes failures (counter)
- [ ] doc write time (?)

## http metrics

- [ ] number of running requests (counter)
- [ ] number of requests (gauge)
- [ ] counters per HTTP status 
- [ ] number of responses sent (gauge)
- [ ] bandwidth usage IN/OUT per socket (gauge)

## node metrics:

- [ ] global memory usage  (gauge)
- [ ] ets usage (gauge)
- [ ] binary usage (gauge)
- [ ] number of processes (gauge)
- [ ] disk size (gauge)

**Comment by BernardNotarianni** [comment]
What about metrics involving durations (or bandwith)? Such as time to insert or read a document?
Would they be computed from the counters by the external monitoring system? 

I understand we should be able to implement some of them inside barrel to be able to implement the back pressure, exact?

**Comment by BernardNotarianni** [comment]
The specifications of those metrics are wrong. First one is a gauge and the remaining are mostly counters.
(As related to #90)

I propose to be more precise on each metrics to determine if it is counter, gauge or histogram and maybe indicate when/where they are measured.

**Comment by benoitc** [comment]
Purpose of this tickets was to list the metrics, counters was just an indication. I now edited the ticket with the correct definition of each metrics.

**Comment by BernardNotarianni** [comment]
I guess *number of docs replicated IN/OUT* should be counter. Correct?

**Comment by benoitc** [comment]
@BernardNotarianni I forgot to remove it, sorry for that. Indeed, at the db level we can only know the number of revisions replicated, which is indeed a counter.

**Comment by benoitc** [comment]
description has been edited.

**Comment by benoitc** [comment]
We talk about that last week, but for the record, indeed one of the goal to achieve there si to have useful metrics to help the back pressure. So indeed we need to have the figures locally and not on a remote system.

**Comment by BernardNotarianni** [comment]
I think I was not clear about "when/where". This issue is more about for each meatric to determine when/where in the excution flow of the code which should make the measure. We could specify that later part of the incremental implementation process.

**Comment by benoitc** [comment]
issue has been moved to gitlab: https://gitlab.com/barrel-db/barrel-platform/issues/81
