### ISSUE TITLE
hooks metrics

### ISSUE THREAD

**Issue by BernardNotarianni** [barrel-db/barrel-platform#87]
This issue follows #84. Also related to #81 

- Introduce a [hook system](https://github.com/benoitc/hooks)
- call hooks each time a metric is updated in `barrel_metrics`

**Comment by BernardNotarianni** [comment]
This is the wrap up of todays discussion about metrics plugin.

The objective is to install a stats plugin infrastructure for metrics inspired by the fuse stats plugin system.

- design a behaviour for metrics (such as [fuse_stats_plugin](https://github.com/jlouis/fuse/blob/master/src/fuse_stats_plugin.erl))
- Instantiate the implementation of the plugin at startup, based on rebar.config
- take over the plugins available in fuse
- add a plugin to send metrics over UDP statsd

The metrics counter will be identified by path such as:
```erlang
InitialValue = 0,
Name = ["replicate", <<"repid">>, "doc_read"],
barrel_metrics:init(Name, InitialValue),
```

**Comment by benoitc** [comment]
Issue has been moved to Gitlab. Please follow the changes there: 
https://gitlab.com/barrel-db/barrel-platform/issues/87
