### ISSUE TITLE
revert "Introduce metrics" commit

### ISSUE THREAD

**Issue by benoitc** [barrel-db/barrel-platform#90]
I accepted it too fast and I think that`eb4c7b8e9c15c400219d5ed2a7b02c1ea39bd347`  must be reverted waiting a proper patch.  

Global metrics on the number of docs replicated reads or write don't give any useful information there, it should be per task only. Also we should make sure that the metric system gives the following features:

- give metrics / database
- give metrics / replication tasks
- give global metrics (http, node, some global metrics)

**Comment by BernardNotarianni** [comment]
Indeed, this commit was a first increment to implement #81 which appears to be erroneous, as we discussed it last saturday

Nevertheless, I suggest to keep it incremental. At the end it would probably implement the features you  list, but it sould be merged into master as several pull requests.

**Comment by benoitc** [comment]
@BernardNotarianni as we discussed this morning, we need at least a first comit that implement the metric as discussed with the hook system. so let's revert it for now and discuss the design of the complete implementation in a separate ticket
