### ISSUE TITLE
ATOMIC attachment upload

### ISSUE THREAD

**Issue by benoitc** [barrel-db/barrel-platform#91]
As discussed with K, we need to add an API to upload atomaticaly the doc with its attachments. The resulting API of the Erlang client will be the following:

### Upload the doc with attachments

* `put(DbName, Doc, Attachments, Option)` where Attachments is a list of attachments:

```erlang
[{“id”: “attachment id”, “content-type”: …, “content-length”: .., “blob”: attachment blob “}]
```

* _discussed with K_: **The blob can be an erlang term that will be encoded to binary**  (using term_to_binary) 
  * If content-type= application/erlang then the blob can be an erlang term 
 * If content type is missing and erlang term is given the content type is set to “application/erlang” and the term encoded
 * Otherwise, it should be a binary

> similar api is used for POST

### Get the doc with its attachments:

* `get(DbName, DocId, [{attachments, all or list of attachments name to get}]). it returns `{ok, Doc, DocMeta, Attachments}`

* _discussed with  K_:  *if binary is an erlang term, it should be automatically decoded*:

  * If content-type=application/erlang then the attachment is returned as an erlang term. 
  * Otherwise, it will be a binary.

### Current implementation:

* We get the document object using GET, 
* We edit the document object and add an “_attachments” property containing the list of attachements description, the blobs are base64 encoded):

```json		
		{
			"Id": "DocId", 
			"_attachements": [
				{
                                  "id": "attachment ID",
                                  "_data": "blob as base64"
                                },
                       ]
              } 
```

### New Implementation

To implement the API above we will simply do the following:

- the attachament description will now be:

```json
{
    "id": "attachment ID",
    "blob": "blob as base64",
    "content-type": "mimetype",
    "content-length": 10
}
```

- if no content type is given there will be 3 cases:
   - the blob given is an erlang term: encoded to binary and the content type is set to `application/erlang`
  - the blob is a binary, the content-type is set to `application/octet-stream`
  - if a blob is an erlang term but the content type differs from `application/erlang` an error is returned-
- the content-length is always set by barrel and replace the existing one if any
- **On GET we remove the `_attachments` part from the JSON received from the server**

### Limitation of the implementation

1. We are for now embedding the full blob in the document while sending it to Barrel. This will be fixed in the next iteration of the API with proper blob storage support.

2. To update/delete an attachment, you need to call function `put(DbName, Doc, Attachments, Option)` with full list of attachments, including those you do not want to update.

**Comment by deadtrickster** [comment]
👍
